version: '3.8'

services:
  agent:
    build: .
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - agent_net
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    environment:
      - DISPLAY

networks:
  agent_net:
    driver: bridge